### ISSUE TITLE
brand: SearXNG

### ISSUE THREAD

**Issue by return42** [searxng/searxng-docker#1]
- fix links from searx to searxng in the README
- what else do we need?
- should we rename the service? https://github.com/searxng/searxng-docker/blob/4ad61d64991d76a7d300b7b867771ffed9f224ca/searx-docker.service.template#L2 https://github.com/searxng/searxng-docker/blob/4ad61d64991d76a7d300b7b867771ffed9f224ca/update.sh#L7
- I think a movement to folder searxng-docker is not needed (?)  https://github.com/searxng/searxng-docker/blob/4ad61d64991d76a7d300b7b867771ffed9f224ca/searx-docker.service.template#L9
- is this valid any longer? https://github.com/searxng/searxng-docker/blob/4ad61d64991d76a7d300b7b867771ffed9f224ca/update.sh#L81-L85
- shuld be renamed to searxng https://github.com/searxng/searxng-docker/blob/4ad61d64991d76a7d300b7b867771ffed9f224ca/update.sh#L92

**Comment by dalf** [comment]
Closed by #2
