### ISSUE TITLE
After a while, no results

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [searxng/searxng-docker#109]
I've run it for the past 2 months, today I can see there are no results (only google as engine)

![image](https://user-images.githubusercontent.com/15908060/209108581-a01e2fea-7930-4961-8340-59d0c568c4d8.png)

Any Idea?

Thanks :)

**Comment by return42** [comment]
> only google as engine)

your instance has been blocked temporary by google .. SearXNG engines has been improved a lot since this thread was opened .. the results should be better these days.  If you have ongoing issue with the engines, please report to https://github.com/searxng/searxng
