### ISSUE TITLE
Getting this error thru portainer. this is the only one with issue.

### ISSUE THREAD

**Issue by mrwestside12** [searxng/searxng-docker#117]
time="2023-01-24T04:29:13Z" level=warning msg="Could not do a head request for \"searxng/searxng:latest\", falling back to regular pull." container=/searxng image="searxng/searxng:latest"
time="2023-01-24T04:29:13Z" level=warning msg="Reason: registry responded to head request with \"404 Not Found\", auth: \"not present\"" container=/searxng image="searxng/searxng:latest"

**Comment by gassssss** [comment]
I have the same issue, arm branch, it's been happening since january 19

**Comment by mrwestside12** [comment]
Thank you. I ended up going with paulgoio version and it doesn't do this?
