### ISSUE TITLE
Very slow requests with Docker

### ISSUE THREAD

**Issue by Neifab** [searxng/searxng-docker#131]
Hello everyone,

I've just installed the last SearXNG with Docker on my server, everything went well but i had only time outs at first, so i have given more request_timeout in the settings and now it's working (10.0 until Google wanted it)

But it's really damn slow. Is this a limitation of my VM Ubuntu system (CPU) ? Is there any tricks to accelarate the requests ?

Thank you very much.

**Comment by Solirs** [comment]
Strange, does the issue keep on going if you run searxng outside of docker from the latest commit? For example git clone the main repo, download the requirements (`pip install -r requirements.txt) and `make run` it?

**Comment by Neifab** [comment]
Ah yes, i will test and let you know.

**Comment by Neifab** [comment]
Ok so i've just stopped and reload SearXNG in Docker and now everything is going fine, i don't understand the cause of this.
