### ISSUE TITLE
Disable TLS in local network

### ISSUE THREAD

**Issue by steponmepls** [searxng/searxng-docker#134]
My home server isn't connected to the outside so caddy isn't able to generate a certificate for me. Every change I make in the UI redirects me to the HTTPS hostname even though the request came from HTTP. I am unsure how to proceed to make the container usable in my local network. I tried commenting out this line but nothing changed:
https://github.com/searxng/searxng-docker/blob/e76656a162c40c04ecc4b119d2a28ec2104c5275/Caddyfile#L36-L37

**Comment by dalf** [comment]
Add the prefix `http://` in front of your hostname here:

https://github.com/searxng/searxng-docker/blob/e76656a162c40c04ecc4b119d2a28ec2104c5275/.env#L6

So for example `http://searxng.lan` instead of `searxng.lan`.

See https://caddyserver.com/docs/automatic-https#activation : 

> Any of the following will prevent automatic HTTPS from being activated, either in whole or in part:
>    * Prefixing the [site address](https://caddyserver.com/docs/caddyfile/concepts#addresses) with http:// in the Caddyfile

**Comment by steponmepls** [comment]
I wasn't able to use `.env`. No changes to the file affected the stack. Since I'm using portainer I manually added the env variables there but now that I added `http://` the home page is broken. There's also this line in the compose that could be causing issues with the hardcoded protocol:

https://github.com/searxng/searxng-docker/blob/e76656a162c40c04ecc4b119d2a28ec2104c5275/docker-compose.yaml#L46
With that said, even when I changed this line to use `http://` I would sill be redirected to HTTPS when changing options in the searx UI

![image](https://user-images.githubusercontent.com/63500907/227795225-87c099d4-1669-45bc-9f78-63c2ffaedb50.png)
![image](https://user-images.githubusercontent.com/63500907/227795339-c9d9aeaf-5141-4488-8bf5-93541e2acf73.png)

**Comment by steponmepls** [comment]
I found the problem. These lines had no port set, so I was being redirected to `:80`

```yaml
    environment:
      - SEARXNG_BASE_URL=http://${SEARXNG_HOSTNAME:-localhost}:8082/
```

Now the UI redirects me back to the home page
