### ISSUE TITLE
Because it violates the following Content Security Policy directive: "form-action 'self'

### ISSUE THREAD

**Issue by Samppady** [searxng/searxng-docker#136]
Hello, 

SearXNG in Settings when I try to save I get an error message in Chrome under Devtools>Network.
And the settings window doesn't close, I have to select the main page.

When I try to use Chrome inside of LAN to Searxng-docker(Caddy) SearXNG in Settings save works fine.
Why does Searxng-docker break when I try to use Reverse Proxy? 

**Firefox works normally.**

**Error:** Refused to send form data to 'https://**/preferences' because it violates the following Content Security Policy directive: "form-action 'self' https://github.com/searxng/searxng/issues/new".

**Response Headers:**
Alt-Svc: h3=":7443"; ma=2592000
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Encoding: gzip
Content-Security-Policy: upgrade-insecure-requests; default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self' https://github.com/searxng/searxng/issues/new; font-src 'self'; frame-ancestors 'self'; base-uri 'self'; connect-src 'self' https://overpass-api.de; img-src 'self' data: https://*.tile.openstreetmap.org; frame-src https://www.youtube-nocookie.com https://player.vimeo.com https://www.dailymotion.com https://www.deezer.com https://www.mixcloud.com https://w.soundcloud.com https://embed.spotify.com
Content-Type: text/html; charset=utf-8
Date: Tue, 28 Feb 2023 12:42:26 GMT
Feature-Policy: accelerometer 'none';ambient-light-sensor 'none'; autoplay 'none';camera 'none';encrypted-media 'none';focus-without-user-activation 'none'; geolocation 'none';gyroscope 'none';magnetometer 'none';microphone 'none';midi 'none';payment 'none';picture-in-picture 'none'; speaker 'none';sync-xhr 'none';usb 'none';vr 'none'
Permissions-Policy: accelerometer=(),ambient-light-sensor=(),autoplay=(),camera=(),encrypted-media=(),focus-without-user-activation=(),geolocation=(),gyroscope=(),magnetometer=(),microphone=(),midi=(),payment=(),picture-in-picture=(),speaker=(),sync-xhr=(),usb=(),vr=()
Pragma: no-cache
Referrer-Policy: no-referrer
Server: nginx
Server-Timing: total;dur=116.484, render;dur=106.75
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Strict-Transport-Security: max-age=31536000; includeSubDomains
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Robots-Tag: noindex, noarchive, nofollow
X-Xss-Protection: 1; mode=block

NGINX reverse-proxy > Searxng-docker

ServerIP: 192.168.0.2
NGINX-reverse-proxy_IP: 192.168.0.14

Searxng-docker http-port: 90
Searxng-docker Caddy https-port: 7443

--- Docker docker-compose.yaml
version: '3.7'

services:

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/data/certs:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost:90}
      - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
     - "0.0.0.0:90:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://${SEARXNG_HOSTNAME:-localhost}:7443/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:
    ipam:
      driver: default

volumes:
  caddy-data:
  caddy-config:

--   .env
SEARXNG_HOSTNAME=192.168.0.2

--- NGINX reverse-proxy
.
.
...

location /searx {
  access_log    off;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
  proxy_cache_bypass $http_upgrade;

  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header Host $proxy_host;
  proxy_set_header X-Script-Name /searx;
  proxy_set_header X-Scheme $scheme;
  proxy_buffering off;

  proxy_pass https://192.168.0.2:7443/;

  proxy_set_header Accept-Encoding "";
  sub_filter "https://192.168.0.2:7443/" "https://domain.com/";
  sub_filter_once off;

}

**Comment by return42** [comment]
> Why does Searxng-docker break when I try to use Reverse Proxy?

Set `base_url` / see https://docs.searxng.org/admin/engines/settings.html#server
