### ISSUE TITLE
Morty generate correct urls for image proxy, but SearXNG try to pull images from wrong urls.

### ISSUE THREAD

**Issue by zigazajc007** [searxng/searxng-docker#14]
You can read everythign here:
https://github.com/searxng/searx-instances/issues/46#issuecomment-1100919668

**Comment by extremelyonline** [comment]
I see that the temporary workaround is to disable Morty. In the SearXNG main page, it's state that "you don't need [Morty] to proxy the images even on a public instance" — what is the privacy implication of not using morty?

**Comment by zigazajc007** [comment]
Yes, I have disabled Morty and everything is works now. Just to let you know about this issue.

**Comment by mrpaulblack** [comment]
@zigazajc007 did you set `SEARXNG_HOSTNAME=domain.com` like so? So without the https protocol part in the .env file? (Since the HTTPS is added automatically)

**Comment by zigazajc007** [comment]
I did that wrong for the first time. But then I have removed all containers and images, removed https:// and reinstalled it. But it still provided https://http//domain.com
