### ISSUE TITLE
Save preferences points to http://localhost:8080 instead of http://myhost:8080

### ISSUE THREAD

**Issue by ToontjeM** [searxng/searxng-docker#164]
Running searxng-docker Powered by SearXNG 2023.7.1+5720844f 

**How did you install SearXNG?**
docker run -d -p ${PORT}:8080 -v "${PWD}/searxng:/etc/searxng" -e "BASE_URL=http://yellow:$PORT/" -e "INSTANCE_NAME=mysearch" --restart unless-stopped searxng/searxng
No docker-compose.

**What happened?**
Access SearX web interface, open Preferences, Save preferences. URL bar shows http://localhost:8080 instead of http://yellow:8080

**Expected behavior**
URL should be http://yellow:8080

**Additional context**
base_url in settings.yml is set to http://localhost:8080 instead of http://yellow:8080. Cannot edit this file.

BTW, i notice that instance name is also no honored.

**Comment by return42** [comment]
> Cannot edit this file.

see https://github.com/searxng/searxng-docker#how-to-use-it

**Comment by AndresJ551** [comment]
Hello,
I have a similar issue while saving the preferences.
I'm using the dockerfile from this repo and [Nginx-Proxy](https://github.com/nginx-proxy/nginx-proxy) 
This are the environment variables:
```
      - VIRTUAL_HOST=search.hardcoredevs.com
      - LETSENCRYPT_HOST=search.hardcoredevs.com
      - VIRTUAL_PORT=8080
      - SEARXNG_HOSTNAME=search.hardcoredevs.com
      - SEARXNG_BASE_URL=https://search.hardcoredevs.com/
      - SEARXNG_PORT=8080
      - SEARXNG_BIND_ADDRESS=0.0.0.0
```
I get a 502 Bad Gateway error after saving the changes on preferences.
Hope you can help me solving this one, I'm loving the project.
