### ISSUE TITLE
Is the image on docker hub official?

### ISSUE THREAD

**Issue by Olejja** [searxng/searxng-docker#168]
Hello.

There is a link in README.md to https://hub.docker.com/r/searxng/searxng I wanted to clarify if this image is official or distributed by third parties?

**Comment by mrpaulblack** [comment]
Hi,
https://hub.docker.com/r/searxng/searxng is officially build by us. Every time there is a commit to the master branch at https://github.com/searxng/searxng -> GitHub actions build and upload the image to dockerhub; Closing.
