### ISSUE TITLE
Favicon docker-compose.yaml

### ISSUE THREAD

**Issue by winkado** [searxng/searxng-docker#171]
I've added the favicon and logo to the docker compose file but it doesnt show up when visiting the website. No errors logged. Any tips?

```
volumes:
   - ./favicon.png:/usr/local/searxng/searx/static/themes/simple/img/favicon.png
   - ./favicon.svg:/usr/local/searxng/searx/static/themes/simple/img/favicon.svg
   - ./searxng.png:/usr/local/searxng/searx/static/themes/simple/img/searxng.png
   - ./searxng.svg:/usr/local/searxng/searx/static/themes/simple/img/searxng.svg
 ```

**Comment by Winkado** [comment]
* I've found the searxng.png on the about page.

**Comment by Winkado** [comment]
The one it should be replacing:
![image](https://github.com/searxng/searxng-docker/assets/47163549/8defd955-5c7b-4185-8f8c-b933c9216c55)

The one it's replacing:
![image](https://github.com/searxng/searxng-docker/assets/47163549/4d447b3e-5c1a-49b1-8c10-54c595172722)

**Comment by unixfox** [comment]
Wrong repository for asking such feature request. And no it's not officially supported.
