### ISSUE TITLE
fix documentation link

### ISSUE THREAD

**Issue by lordkitsuna** [searxng/searxng-docker#173]
in the settings yml there is this link "https://docs.searxng.org/admin/engines/settings.html#use-default-settings" however its a dead link. if you dig around you can find https://docs.searxng.org/admin/installation-searxng.html#configuration however that config looks nothing like the one found in this repo and has several options this one does not so i have no idea if its relevant or not

**Comment by dalf** [comment]
Thank you for reporting this issue.

See https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings 

With `use_default_settings: true`, the configuration is based on [the default settings.yml](https://github.com/searxng/searxng/blob/master/searx/settings.yml) --> `searxng/settings.yml` describes only the changes from that default settings.

You can specify a full configuration by removing `use_default_settings: true`.
