### ISSUE TITLE
How to change the listening port inside the container/image?

### ISSUE THREAD

**Issue by TomErnst1972** [searxng/searxng-docker#175]
Hi,

I'm using the docker version today with -p 8123:8080, but I'd like to be able to use --net=host, therefore I'd like to ask if there is some "-e WHATVER_VARIABLE=PORTNUMBER" to achieve this.

Basically the internal listening port has to be changed from outside (docker run, or docker-compose.yaml)

Changing this:
-e "BASE_URL=http://my.base.url:6766/" \

or trying
-e PORT=6766 

didnt help.  Any ideas? 

best regards,
Tom

**Comment by StarryMoe** [comment]
Hi,

Please try:
`BIND_ADDRESS=0.0.0.0:6766`

It works for me. The reason is here: #20

**Comment by TomErnst1972** [comment]
yeah, found that out, too. Here's what I use:
docker run --restart always -d --net=host \
          -e BIND_ADDRESS=0.0.0.0:6766 \
          -e DEFAULT_BIND_ADDRESS=0.0.0.0:6766 \
          -v "/opt/searx:/etc/searxng" \
          -e "BASE_URL=http://xxx.yyy.zzz/" \
          -e "INSTANCE_NAME=searxNG" \
          --name search \
 searxng/searxng
