### ISSUE TITLE
searxng preferences forgotten sometimes in FireFox

### ISSUE THREAD

**Issue by privacyguy123** [searxng/searxng-docker#176]
Can't understand exactly what could be causing this ... I have the cookie explicitly saved so it never gets removed on close/clean.

**Comment by privacyguy123** [comment]
Now searching from URL bar then searching again inside that already opened page defaults my search to just "IT" rather than all the options I've selected. Wtf is going on here?

**Comment by privacyguy123** [comment]
Someone can look into this bug? It's driving me loopy

**Comment by Bnyro** [comment]
That's not an issue of this repo.

**Comment by Bnyro** [comment]
Close this one and create one at the main repo.
