### ISSUE TITLE
How to modify filtron settings for Docker instance of SearXNG?

### ISSUE THREAD

**Issue by CrazyPython** [searxng/searxng-docker#18]
I'm trying to allow JSON search requests. How do I modify filtron settings for searxng docker?

**Comment by mrpaulblack** [comment]
hi @CrazyPython ,

We are not using filtron in our SearXNG docker stack anymore. We switched to using a limiter plugin in SearXNG itself in conjunction with redis as a store for hosts (we dont store the IP as cleartext, but rather as a hash)...

There is a default limit of 4 requests per hour:
https://github.com/searxng/searxng/blob/ca1a5f9d270696a917aef9c411c9671255732281/searx/plugins/limiter.py#L71

You can change this by modifying the 4 right here to something larger:
https://github.com/searxng/searxng/blob/ca1a5f9d270696a917aef9c411c9671255732281/searx/plugins/limiter.py#L73

If you use docker you can make the changes to that file and mount it inside the `searxng/searxng` container in the following directory:
```yaml
- ./limiter.py:/usr/local/searxng/searx/plugins/limiter.py
```


Also please dont forget to enable API requests in your `settings.yml`:
https://github.com/searxng/searxng/blob/ca1a5f9d270696a917aef9c411c9671255732281/searx/settings.yml#L39

Please write a quick comment if this helped so I can close the issue :+1:
