### ISSUE TITLE
Need Docker Compose Sanitation

### ISSUE THREAD

**Issue by techwithjake** [searxng/searxng-docker#186]
I created my docker compose and in it I had

`- INSTANCE_NAME="NAME GOES HERE"`

The created settings.yml added the quotation marks as the instance name. Since the settings.yml adds quotation marks as well, there's two pairs and prevents SearxNG from loading.

Relevant log failures

`  File "/usr/lib/python3.11/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/etc/searxng/settings.yml", line 3, column 3
expected <block end>, but found '<scalar>'
  in "/etc/searxng/settings.yml", line 5, column 20`

There needs to be some kind of sanitation to prevent the quotation marks being pulled in.

**Comment by unixfox** [comment]
See here why you don't always need to add quotation marks: https://stackoverflow.com/questions/53082932/yaml-docker-compose-spaces-quotes

**Comment by return42** [comment]
just for reference --> [For a data format, yaml is extremely complicated. It aims to be a human-friendly format, but in striving for that it introduces so much complexity, that I would argue it achieves the opposite result. Yaml is full of footguns and its friendliness is deceptive.](https://ruudvanasseldonk.com/2023/01/11/the-yaml-document-from-hell)
