### ISSUE TITLE
Running searxng-docker as a service starts w/ no errors. but browser reports Error code: PR_CONNECT_RESET_ERROR

### ISSUE THREAD

**Issue by GlenC289** [searxng/searxng-docker#189]
I installed back in January and things have been running great.  A few days ago, I found out that a "git pull" was required as part of the update process in addition to the "docker-compose pull". After updating, I noticed that I was receiving the above error in Firefox when starting the containers with systemd. If I started the containers using "docker-compose UP" instead, everything appeared normal.

I suspected that since I had never done a "git pull" prior to "docker-compose pull" that maybe something had gotten corrupted.  I decided that it would be easiest just to completely rebuild my Linode on Akamai. Despite starting from scratch, I still have the same symptoms.

I don't see any similar issues posted so any ideas would be appreciated.

**Comment by unixfox** [comment]
Check the logs

**Comment by GlenC289** [comment]
Thank you! It turns out searxng-docker.service file pointed to /usr/local/bin/ for the docker-compose file and mine are located in /usr/bin/.

The instructions alerted me to check the location of the working directory but it should probably address the  two locations for the docker-compose files too (for people like me).
