### ISSUE TITLE
realpath() of /etc/searxng/uwsgi.ini failed: Permission denied [core/utils.c line 3662]

### ISSUE THREAD

**Issue by schklom** [searxng/searxng-docker#19]
This is meant for people who (like me) have the following error when starting the `searxng` container
```sh
realpath() of /etc/searxng/uwsgi.ini failed: Permission denied [core/utils.c line 3662]
```

It turns out that the volume `searxng` defined in
https://github.com/searxng/searxng-docker/blob/ba1569dafb1c7737f3b18f86a4ab0e6ceb14f8fc/docker-compose.yaml#L44-L45

must have permission 755. Setting permission 750 causes the error above.

Hope it helps someone.

**Comment by james-still** [comment]
@schklom Would you be able to create a PR of the fix? I'm having the same error - and trouble setting the permissions to 755. Thanks.

**Comment by schklom** [comment]
@james-still It turns out that the user `searxng` (id 977) needs to have access to the files. So setting folder permissions to 700 works, as long as the folder belongs to `searxng`.

You can do this with (maybe need sudo)
```bash
chown -R 977:977 ./searxng
chmod 700 ./searxng
chmod 600 ./searxng/*
```

On my machine it now looks like
```bash
$ sudo ls -alh searxng/
total 17K
drwx------  2    977    977 4.0K Jul  8 17:29 .
drwxrwxr-x 11 ubuntu ubuntu 4.0K Jul  7 22:44 ..
-rw-------  1    977    977 2.6K Jul  7 18:46 settings.yml
-rw-------  1    977    977 1.1K Jul  8 17:29 uwsgi.ini
```

**Comment by schklom** [comment]
You are not supposed to have one. The searxng Docker container defines that user internally by using the id 977.
Just use 977. Then, if you go inside the container and look who owns those files, it will show up as the user "searxng".

**Comment by Magicrafter13** [comment]
Then how can I fix this permissions error? Setting the permissions to 755 is unacceptable since the settings file contains a secret key, which should not be readable by all users on the system.

**Comment by schklom** [comment]
@Magicrafter13 https://github.com/searxng/searxng-docker/issues/19#issuecomment-1179227055

**Comment by Magicrafter13** [comment]
oh right... thanks

not sure why I didn't connect the dots - kinda concerning actually
