### ISSUE TITLE
Changing server port cannot be done via settings.yaml

### ISSUE THREAD

**Issue by schklom** [searxng/searxng-docker#20]
Setting
```yaml
server:
  port: 1234
```
in `settings.yaml` does not make the Docker container listen on 0.0.0.0:1234.

Only setting
```yaml
    environment:
      BIND_ADDRESS: 0.0.0.0:1234
```
in `docker-compose.yaml` makes it work.

`settings.yaml` is not taken into account for the port, but there is a workaround.
Does setting the `settings.yaml` port number do anything?

EDIT: I found the workaround by looking at the entrypoint script of the Dockerfile https://github.com/searxng/searxng/blob/31521f3a465fa2beb7e3fd7ed47621262a28f554/dockerfiles/docker-entrypoint.sh#L26-L27:
```sh
export DEFAULT_BIND_ADDRESS="0.0.0.0:8080"
export BIND_ADDRESS="${BIND_ADDRESS:-${DEFAULT_BIND_ADDRESS}}"
```

**Comment by l2evy** [comment]
I can confirm this issue still persist as of now.

**Comment by dalf** [comment]
I'm sorry for the delay.

If you talk about the Caddy image, just change Caddy configuration since the network is the one from the host:
https://github.com/searxng/searxng-docker/blob/ba1569dafb1c7737f3b18f86a4ab0e6ceb14f8fc/docker-compose.yaml#L8

If you talk about the SearXNG image, change this line:
https://github.com/searxng/searxng-docker/blob/ba1569dafb1c7737f3b18f86a4ab0e6ceb14f8fc/docker-compose.yaml#L43

**Comment by schklom** [comment]
@dalf I was talking about the SeaXNG image.
Changing
https://github.com/searxng/searxng-docker/blob/ba1569dafb1c7737f3b18f86a4ab0e6ceb14f8fc/docker-compose.yaml#L43
only maps ports, it doesn't make the image communicate via a port other than 8080.

I mean that I can use
```yaml
 - "127.0.0.1:8080:9999" 
```
but the port that the container sends data through remains 8080 despite 9999 being exposed. The port 9999 will not transfer data on its own.

A possible fix would be to amend
https://github.com/searxng/searxng/blob/f814ac703b25640d28ab3a4a096f693808cde6db/dockerfiles/docker-entrypoint.sh#L26
```sh
export DEFAULT_BIND_ADDRESS="0.0.0.0:8080"
export BIND_ADDRESS="${BIND_ADDRESS:-${DEFAULT_BIND_ADDRESS}}"
```
into
```sh
export DEFAULT_BIND_ADDRESS="0.0.0.0:${BIND_PORT:-8080}"
export BIND_ADDRESS="${BIND_ADDRESS:-${DEFAULT_BIND_ADDRESS}}"
```
and pass `BIND_PORT` as a Docker environment variable.

**Comment by dalf** [comment]
I don't understand the use case: since your change the port mapping, when you do need to change the listening port inside the docker image?

**Comment by schklom** [comment]
I pass this container's network via a vpn container. The vpn container then exposes ports to my local network. Another container (passed through the vpn container) uses internal port 8080 and cannot be changed. SearXNG and that other container cannot coexist.

In case I am not clear, this is the port setup I would like but cannot achieve
```yaml
  vpn:
    ports:
      - 8080:8080 # Libreddit
      - 8081:8080 # SearXNG
  
  searxng:
    network_mode: service:vpn
```
Libreddit forces port 8080. SearXNG as well unless I use an undocumented environment variable (c.f. first post).

This is not a major issue and I provided a hacky solution. The problem is that the documentation in settings.yaml is wrong, and I wanted to show away to do it, in case anyone else has the same issue.

**Comment by cochunni** [comment]
I could see that caddy was drying without any error when I tried shaping the port binding too !!

**Comment by quadcom** [comment]
I have mine on a dedicated IP, on Unraid via a MACVLAN and cannot hit the server on port 80. It's hard-coded to port 8080. This is nuts.

**Comment by EoinD123** [comment]
This is still present. Playing around with it the only thing that worked was in Docker Compose placing:
`          environment:
               - BIND_ADDRESS=0.0.0.0:8888`
Any variation in the settings.yaml had no effect on the bound port (default 8080).

**Comment by garagetrader** [comment]
> I pass this container's network via a vpn container. The vpn container then exposes ports to my local network. Another container (passed through the vpn container) uses internal port 8080 and cannot be changed. SearXNG and that other container cannot coexist.
> 
> In case I am not clear, this is the port setup I would like but cannot achieve
> 
> ```yaml
> services:
>   vpn:
>     ports:
>       - 8080:8080 # Libreddit
>       - 8081:8080 # SearXNG
>   
>   searxng:
>     network_mode: service:vpn
> ```
> 
> Libreddit forces port 8080. SearXNG as well unless I use an undocumented environment variable (c.f. first post).
> 
> This is not a major issue and I provided a hacky solution. The problem is that the documentation in settings.yaml is wrong, and I wanted to show away to do it, in case anyone else has the same issue.

I'm here for this exact same issue with the same 2 containers. Thanks for working on this ahead of me.

**Comment by Bnyro** [comment]
The intended way to set the port when using Docker is to use the `BIND_ADDRESS` environment variable, the searxng-docker documentation just lacks information on how to self-host without Caddy so far. Documentation on that will be added with #285.

**Comment by schklom** [comment]
@Bnyro Shouldn't https://github.com/searxng/searxng/blob/master/searx/settings.yml be updated as well by removing the `port` line on

https://github.com/searxng/searxng/blob/5332d3a0b8f94a7a984d22cbcfa1fb9c34cb3ff9/searx/settings.yml#L77-L79

```yaml
server:
  # Is overwritten by ${SEARXNG_PORT} and ${SEARXNG_BIND_ADDRESS}
  port: 8888
```
?

**Comment by Bnyro** [comment]
No, it's used by non-docker-deployments.

**Comment by limdingwen** [comment]
Note that since the switch to Granian, the new environment variable to set is `GRANIAN_PORT`.

For example:

```
services:
  searxng:
    image: searxng/searxng
    restart: unless-stopped
    environment:
      - GRANIAN_PORT=80
    volumes:
      - ./config:/etc/searxng:ro
      - ./data:/var/cache/searxng
```
