### ISSUE TITLE
We have Reverse Proxy at home

### ISSUE THREAD

**Issue by codingneko** [searxng/searxng-docker#208]
Hi, just a suggestion. 
Not sure if this is just my experience of anyone else experienced this, but please add warning signs and neon hecking text somwehre warning that this thing comes bundled with Caddy and WILL prevent anything on port 80 and 443 from running if made to auto-start (I know it says it comes with Caddy on the README.md but I'm stupid and other people probably are too), because I just had my Nginx server murdered by this thing's Caddy (it loaded before nginx did and nginx couldn't use port 80 and 443). Most people probably already have a reverse proxy installed, and this is going to prevent it from starting.

Anyway, thanks for making this thing!

**Comment by unixfox** [comment]
https://github.com/searxng/searxng-docker/issues/85
https://github.com/searxng/searxng-docker/issues/199
https://github.com/searxng/searxng-docker/issues/15
