### ISSUE TITLE
Secret Key Generation returns error: sed: 1: "searxng/settings.yml": unterminated substitute in regular expression

### ISSUE THREAD

**Issue by Bombenheimer** [searxng/searxng-docker#231]
When generating a secret key with ```sed -i "s|ultrasecretkey|$(openssl rand -hex 32)|g" searxng/settings.yml```, I get an error that says ```sed: 1: "searxng/settings.yml": unterminated substitute in regular expression```. I am using macOS Sonoma 14.4.1

**Comment by Bnyro** [comment]
Try `sed -i"" -e "s|ultrasecretkey|$(openssl rand -hex 32)|g" searxng/settings.yml` which should work on MacOS too.
