### ISSUE TITLE
Arm/v7 dropped from upstream on Valkey?

### ISSUE THREAD

**Issue by uwidev** [searxng/searxng-docker#239]
On my Raspberry Pi 4B, it went offline for a bit. I had to to reset the server and bring it up, but it wasn't working. Seems like it was pulling the image for Valkey (redis) and stated that there's no matching manifest for linux/arm/v7. Did they drop support for v7 or something?

**Comment by uwidev** [comment]
I decided to build it on my local system, which it was able to do. Not too sure why I wasn't able to just pull it.

For anyone running into a similar issue, here's how I built it. It should be relatively straight-forward if you've built an image before.
1. Clone the valkey repo
`https://github.com/valkey-io/valkey-container/tree/mainline`

2. Run their `update.sh` script.
You need bashbrew. Download the one for your architecture from their website.
https://github.com/valkey-io/valkey-container/tree/mainline

Move it to where you store your executables, say `/usr/local/bin`. You should rename it to, or alias, it as `brewbash`.
Also install the `jq` package.

3. Go to `7.2/debian` (or alpine depending on your system), and build your image.
`docker build -t valkey-local .`

In searxng-docker, change value for `image` under `redis` to `valkey-local`.

Again, I have no idea why I wasn't able to pull it. Perhaps they don't pre-build it for arm7 or something. Hopefully someone with better detective work and who better knows what they're looking at could shed some light.

**Comment by unixfox** [comment]
Indeed valkey docker image hasn't been built for ARMv7: https://hub.docker.com/r/valkey/valkey/tags

We didn't really think about it when we switched to valkey docker image. I did a quick search and couldn't find any other well maintained docker image for valkey that is built for ARMv7.

I guess we will have to add a disclaimer of some sort that searxng-docker only support AMD64 and ARM64.

Do note that it is becoming quite rare to have docker images built for ARMv7 so you should look into reinstalling your RPI in ARMv8.

**Comment by xxnuo** [comment]
> I decided to build it on my local system, which it was able to do. Not too sure why I wasn't able to just pull it.
> 
> For anyone running into a similar issue, here's how I built it. It should be relatively straight-forward if you've built an image before.
> 
> 1. Clone the valkey repo
>    `https://github.com/valkey-io/valkey-container/tree/mainline`
> 2. Run their `update.sh` script.
>    You need bashbrew. Download the one for your architecture from their website.
>    https://github.com/valkey-io/valkey-container/tree/mainline
> 
> Move it to where you store your executables, say `/usr/local/bin`. You should rename it to, or alias, it as `brewbash`. Also install the `jq` package.
> 
> 3. Go to `7.2/debian` (or alpine depending on your system), and build your image.
>    `docker build -t valkey-local .`
> 
> In searxng-docker, change value for `image` under `redis` to `valkey-local`.
> 
> Again, I have no idea why I wasn't able to pull it. Perhaps they don't pre-build it for arm7 or something. Hopefully someone with better detective work and who better knows what they're looking at could shed some light.

Can you publish it to somewhere?

**Comment by inetol** [comment]
Upstream PR: https://github.com/valkey-io/valkey-container/pull/25

**Comment by roshkhatri** [comment]
Merged the PR and added support for Arm/v7
