### ISSUE TITLE
cap_drop option prevents uwsgi file creation, resulting in an error

### ISSUE THREAD

**Issue by nakoo** [searxng/searxng-docker#252]
```bash
SearXNG version 2024.7.29+98c73010f
Create /etc/searxng/uwsgi.ini
cp: can't create '/etc/searxng/uwsgi.ini': Permission denied
sed: /etc/searxng/uwsgi.ini: No such file or directory
Use existing /etc/searxng/settings.yml
Listen on 0.0.0.0:8080
realpath() of /etc/searxng/uwsgi.ini failed: No such file or directory [core/utils.c line 3640]
```
I used default docker-compose.yml and have permission issue even with `rw`
After try and error, I found it was `cap_drop` issue, and removing those parts fixed this issue.

if uwsgi.ini is intended to store in config, I feel it needs to be documented.

Related:
https://github.com/searxng/searxng-docker/issues/115
https://github.com/searxng/searxng-docker/pull/238

**Comment by Bnyro** [comment]
Instructions on removing `cap_drop: -ALL` on first run were merged with https://github.com/searxng/searxng-docker/pull/258.
