### ISSUE TITLE
Insecure setup

### ISSUE THREAD

**Issue by xxxcrow** [searxng/searxng-docker#26]
Hi, I just updated seaxng and a lot of things have changed
On my machine ports 80 and 443 are already taken
I'm using a reverse proxy of my hosting panel to forward all the stuff
So I just need searxng to be in plain http on any chosen port

I tried changing ports in docker-compose.yml, removing network: host, editing caddyfile
I got it starting up, and the main page is working, but not the search itself
It seems I'm missing something here
Thank you

**Comment by meichthys** [comment]
I'm also having an issue getting plain http docker-compose configuration.
Removing the caddy service and updating the ports in the searxng service doesn't seem to be sufficient.

**Comment by SuperSandro2000** [comment]
> Insecure setup

That setup is not insecure if TLS is handled by another reverse proxy. Titling this like this is just confusing.

Of course you most likely need to adapt the docker-compose file if you already have other services running. It should be used as an example or template to know how to get things running.

**Comment by mrpaulblack** [comment]
Agreed. I think we could add an examples folder with basic example like nextcloud for example: https://github.com/nextcloud/docker/tree/master/.examples

**Comment by xxxcrow** [comment]
Awesome 😋
I tried my best making it working
It's been already 2 week since my searx stopped working
But I still didn't change any settings in my browsers, so now every time I type duckduckgo 🙂

**Comment by return42** [comment]
> I got it starting up, and the main page is working, but not the search itself
> It seems I'm missing something here

Set `base_url` ->  https://docs.searxng.org/admin/engines/settings.html#server
