### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by Atlas7005** [searxng/searxng-docker#27]
After I followed the instructions in the README - All I got when visiting the URL was a blank white page.

**Comment by AlexandreFigard** [comment]
I tried to installed it 3 times on different server and i'm still getting a blank page

**Comment by mrpaulblack** [comment]
@AlexandreFigard can you please open the dev tools of your Browser with F12 and go to the network tab. Try to do another search or reload the page if it is just white...

Is there a HTTP 429 request? In that case the limiter plugin in SearXNG is blocking your request. You can disable it by adding `limiter: false` to your `settings.yml` config file of SearXNG here: https://github.com/searxng/searxng/blob/5c1c0817c3996c5670a545d05831d234d21e6217/searx/settings.yml#L59

**Comment by AlexandreFigard** [comment]
All seems good but always getting blank page
Others people are having same problem 
No solution at this time

**Comment by Atlas7005** [comment]
I fixed it by downloading using some other instructions from somewhere else. I can't actually quite remember from where, sorry :/

**Comment by smcclosr** [comment]
Seeing the same problem Ubuntu 22.04, tries to load favicon.ico with a 200

**Comment by vsr3y** [comment]
I solved this problem by [not typing a tab character in `searxng/settings.yml`](https://github.com/searxng/searxng/issues/1399#issuecomment-1433708496).
