### ISSUE TITLE
searxng in a lan enviroment

### ISSUE THREAD

**Issue by blub4747** [searxng/searxng-docker#271]
Hello,
I want to the searxng docker container in my local lan.
I am using pihole v6 as my DNS local server. Which adds to each device  .lan address.
Eg mysearxng.lan via a CNAME entry to this box.

However when I try to access mysearxng.lan the client is not resolving to mysearxng.lan.
For now only localhost:8080 works. but when I try to access myearxng.lan or without .lan things will not resolv. 
I also tried adding a mysearxng entry to my local hosts file.
Does anybody have a idea where things might be going wrong ?
thx, blub4747

**Comment by return42** [comment]
You have created an error report here in the searxng-docker image, but what you are asking is a question that concerns a very specific problem in your network / not an error of searxng-docker. 

On the one hand, you will not get an answer here, on the other hand, these questions lead to an increase in error reports that are not errors.

There is an active community in which questions like this are more appropriate and the chance of an answer or discussion is also higher.  I will delete this ticket now, please contact our community --> [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org)
