### ISSUE TITLE
Problem with duckduckgo when seraching in hebrew

### ISSUE THREAD

**Issue by ShlomiD83** [searxng/searxng-docker#298]
![Screenshot_20241116_221012_Chrome](https://github.com/user-attachments/assets/fb377828-3b95-428e-a6a5-45cfc92d99a4)
Whenever I search in Hebrew using DDG i get weird results, please see attached pictures. 
![Screenshot_20241116_221019_Chrome](https://github.com/user-attachments/assets/b42ee43a-5e3a-48f5-beb7-56714338e3c2)

Problem started with 14.11 version, rolling back to one previous version mitigates the issue.

**Comment by return42** [comment]
Closed by: https://github.com/searxng/searxng/pull/4021
