### ISSUE TITLE
rules.json : allow /image_proxy

### ISSUE THREAD

**Issue by dalf** [searxng/searxng-docker#3]
`/image_proxy` can replaced Morty even on a public instance.

`rules.json` should not block the requests to this URL, or at least differently.

For reference https://github.com/paulgoio/searxng/blob/main/src/rules.json

**Comment by dalf** [comment]
Since the limiter ( https://github.com/searxng/searxng/pull/618 ) is merged.
* filtron & morty can be removed
* caddy can target directly searxng on port 8080
* add redis

So I guess this issue can closed?

**Comment by mrpaulblack** [comment]
I will setup my prod with redis and limiter :+1:

**Comment by mrpaulblack** [comment]
Ok the limiter is deployed in production: https://paulgo.dev/paulgoio/searxng/-/pipelines/388 . Lets give the change a week before applying the change in searxng-docker :+1:
