### ISSUE TITLE
Is there a way to customize the logo?

### ISSUE THREAD

**Issue by AleksCee** [searxng/searxng-docker#34]
Hi, I don't want to disguise the excellent work of this project, but I like to change the logo about the seach input to customize the page a little bit. The donation link an anything else I don't want to change, only the logo-image. 

Sorry for this perhaps stupid question.

Thanks, Alex

**Comment by mrpaulblack** [comment]
Hi @AleksCee ,

there are already some discussion on changing the logo in searxng/searxng: https://github.com/searxng/searxng/discussions?discussions_q=logo

here is one for docker on how to change the favicon: https://github.com/searxng/searxng/discussions/1122

you can just modify it to something like this (add this to SearXNG service in `docker-compose.yml`):

```yaml
  volumes:
    - ./searxng.png:/usr/local/searxng/searx/static/themes/simple/img/searxng.png
    - ./searxng.svg:/usr/local/searxng/searx/static/themes/simple/img/searxng.svg
```

Does this help?

**Comment by AleksCee** [comment]
Hi @mrpaulblack thank you! I will give it a try tomorrow.
Thanks, Alex
