### ISSUE TITLE
[bug] fix searxng-docker.service.template

### ISSUE THREAD

**Issue by Dennis102** [searxng/searxng-docker#41]
The following error message appears when I run `systemctl start searxng-docker.service` and check the status afterwards with `systemctl status searxng-docker.service`:
```
● searxng-docker.service - SearXNG service
     Loaded: loaded (/etc/systemd/system/searxng-docker.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2022-07-24 06:58:33 UTC; 4s ago
    Process: 2454 ExecStart=/usr/local/bin/docker-compose -f ${SEARXNG_DOCKERCOMPOSEFILE} up --remove-orphans (code=exited, status=203/EXEC)
   Main PID: 2454 (code=exited, status=203/EXEC)

Jul 24 06:58:33 ip-127-0-0-1 systemd[1]: searxng-docker.service: Scheduled restart job, restart counter is at 5.
Jul 24 06:58:33 ip-127-0-0-1 systemd[1]: Stopped SearXNG service.
Jul 24 06:58:33 ip-127-0-0-1 systemd[1]: searxng-docker.service: Start request repeated too quickly.
Jul 24 06:58:33 ip-127-0-0-1 systemd[1]: searxng-docker.service: Failed with result 'exit-code'.
Jul 24 06:58:33 ip-127-0-0-1 systemd[1]: Failed to start SearXNG service.
```
Installation path is default: /usr/local/searxng-docker
I did not change anything in the file searxng-docker.service, because the installation path did not change.
Am I doing something wrong?

**Comment by Kweetwel** [comment]
There seems to be a typo or error in the template. The docker-compose binary isn't located at /usr/local/bin.... but at /bin/docker-compose.

It changed it in the file 'searxng-docker.service` to the correct path and it worked for me.

```[Unit]
Description=SearXNG service
Requires=docker.service
After=docker.service

[Service]
Restart=on-failure

Environment=SEARXNG_DOCKERCOMPOSEFILE=docker-compose.yaml

WorkingDirectory=/usr/local/searxng-docker
ExecStart=/bin/docker-compose -f ${SEARXNG_DOCKERCOMPOSEFILE} up --remove-orphans
ExecStop=/bin/docker-compose -f ${SEARXNG_DOCKERCOMPOSEFILE} down

[Install]
WantedBy=multi-user.target
```

Don't forget to `systemctl enable /usr/local/searxng-docker.service` and `systemctl start searxng-docker.service` after you made the change. ;)

**Comment by Vogelmonster** [comment]
Works perfectly now! 

Thanks for the quick help :D

**Comment by return42** [comment]
> There seems to be a typo or error in the template. 

Thanks a lot for you feedback :+1: .. which Linux distribution do you use?

.. from the [Filesystem Hierarchy Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard#Directory_structure) I would expect the `docker-compose` command in `/usr/bin`.

**Comment by Kweetwel** [comment]
I use Ubuntu 22.04. I don't know what is 'best practice', but there are two places where you can find the command. In `/bin` and in `/usr/bin`.

'/usr/local/bin` in my case was the wrong path. ;)

**Comment by return42** [comment]
>  In `/bin` and in `/usr/bin`

@Kweetwel thanks a lot for checking this 

@paul @dalf I think we should modify the template to `/usr/bin`

**Comment by mrpaulblack** [comment]
@return42 it depends on how the docker-compose binary was installed with a package manager its at /usr/bin/docker-compose and with the install steps from docker website its at: /usr/local/bin/docker-compose /bin is only a symlink to /usr/bin so it would break for people using install method from docker website
a hacky solution could be: run /usr/bin/which docker-compose and pass that as an argument to ark or something to run it with that path...

**Comment by return42** [comment]
In the `[Service]` section ..

https://github.com/searxng/searxng-docker/blob/f2f9e2ad086c68443c3457a82cf2e368aaa4bc99/searxng-docker.service.template#L6-L13

we can add a `PATH` variable to the environment:

```
Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"
```

**Comment by robertrud** [comment]
My docker compose is installed as a plugin. I found it in /usr/libexec/docker/cli-plugins/
It works now after adjusting the path in service template accordingly.

**Comment by lemonadeforlife** [comment]
Well for me I just replace the hyphen with space that's it. :)
Since I don't have it on my /bin & I installed it as a plugin so it's in docker-plugin directory.

```
ExecStart=/usr/local/bin/docker compose -f ${SEARXNG_DOCKERCOMPOSEFILE} up --remove-orphans
ExecStop=/usr/local/bin/docker compose -f ${SEARXNG_DOCKERCOMPOSEFILE} down
```

**Comment by unixfox** [comment]
@lemonadeforlife please create a PR :)!
