### ISSUE TITLE
HTTP/3 Support for SearXNG

### ISSUE THREAD

**Issue by rattfieldnz** [searxng/searxng-docker#42]
I've recently learned that HTTP/3 is supported by Caddy from version 2.0 and up. Are there plans to support that in SearXNG? I have attempted to make it work for SearXNG (via https://ma.ttias.be/how-run-http-3-with-caddy-2/), but doing so results in a 'ERR_CONNECTION_REFUSED' error in the browser. 

I know that HTTP/3 uses UDP, so have already configured the firewall (ufw) in my server (Amazon EC2) to allow incoming UDP for ports 80 and 443. Incoming Rules on Amazon EC2 instance has also been configured to handle incoming UDP.

I am currently running Ubuntu 22.04 x64 for the server.

**Comment by dalf** [comment]
In Caddyfile, replace [line 1 to 3](https://github.com/searxng/searxng-docker/blob/f2f9e2ad086c68443c3457a82cf2e368aaa4bc99/Caddyfile#L1-L3) by
```yaml
{
  admin off

  servers :443 {
     protocol {
        experimental_http3
     }
  }
}
```

Documentation: https://caddyserver.com/docs/caddyfile/options#protocol

**Comment by rattfieldnz** [comment]
Ah I put those lines in the wrong place initially. Now it works - thanks!
