### ISSUE TITLE
Searxng search timeout

### ISSUE THREAD

**Issue by MaJoRX0** [searxng/searxng-docker#45]
OS : ubuntu server

Hi guys so i installed searxng in my local server and its working fine but after i installed pi-hole i had to stop resolved service and set custom DNS in resolve.conf file, after that searxng search wont work everytime i try to search for anything it just shows me

Error Engines cannot retrieve results

How i can fix this?

**Comment by return42** [comment]
duplicate: https://github.com/searxng/searxng/issues/1563
