### ISSUE TITLE
Cloning Linux

### ISSUE THREAD

**Issue by maximfedorchak1** [searxng/searxng-docker#47]
Trying to use "git clone https://github.com/searxng/searxng-docker.git" but I keep getting "fatal: could not create work tree dir 'searxng-docker': Permission denied". Picture of my terminal below:
![Screen Shot 2022-07-28 at 13 07 17](https://user-images.githubusercontent.com/107649206/181627684-4bfc4fa2-16b0-4436-965d-1af87e72d1c8.png)
Thanks

**Comment by return42** [comment]
The message is self explaining .. `maxim` do not have write permission to `/usr/local`.
