### ISSUE TITLE
Nothing rendered

### ISSUE THREAD

**Issue by ZackeryBayle** [searxng/searxng-docker#50]
This is my first setup. I am getting nothing rendered to the page. the only error I have from the console is  `Uncaught TypeError: Cannot read properties of undefined (reading 'encrypt')`

Linux, Ubuntu LTS 20.XX
current Docker install
current searxng install

please let me know if their is any other info I can provide.

**Comment by vsr3y** [comment]
I solved this problem by [not typing a tab character in `searxng/settings.yml`](https://github.com/searxng/searxng/issues/1399#issuecomment-1433708496).
