### ISSUE TITLE
Searxng image throws exceptions at launch: searx.engines.wikidata: Fail to initialize

### ISSUE THREAD

**Issue by ItalianJack** [searxng/searxng-docker#52]
I've successfully launched the docker image on my laptop, but can't get it working on my server. I'm pretty sure it's got to do with my networking configuration; I've changed the host machine's OS to work with my pihole instance. Based on these errors however, I can't really figure out whats going wrong.

Log is too long for GH; pastebin: https://pastebin.com/xaRaDPDE

**Comment by return42** [comment]
You have a lot off

    ValueError: 'soundcloud.com' does not appear to be an IPv4 or IPv6 address

I assume there is something with your DNS.

**Comment by ItalianJack** [comment]
It was DNS, thanks! Not sure why (not specified in its docker-compose file) but my PiHole instance created its own docker network rather than using the default bridge. I added the searxng and redis images to the network, and specified the DNS server for the searxng image to the IP address of the PiHole instance. Everything worked after that.
