### ISSUE TITLE
Certain URLs are stuck as http://localhost

### ISSUE THREAD

**Issue by n3rd3x3** [searxng/searxng-docker#54]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2022.04.06-4135a740
**How did you install SearXNG?**
 Using searxng-docker
**What happened?**
Certain parts of the website use localhost instead of the specified domain name, such as redirecting the user to `localhost` after saving settings, and setting localhost as the search URL (see below image.)
![Screenshot from 2022-04-06 13-39-45](https://user-images.githubusercontent.com/57784409/162045548-c9d46103-2008-4f6b-a125-8aade0f36037.png)

**How To Reproduce**
1. Install SearXNG using docker-compose
2. Forward port 8080 to port 80 (I used nginx for this)
3. Observe issues listed above

**Expected behavior**
The domain name would be dynamically changed to reflect the domain name you are currently on.

**Screenshots & Logs**
![Screenshot from 2022-04-06 13-39-45](https://user-images.githubusercontent.com/57784409/162045548-c9d46103-2008-4f6b-a125-8aade0f36037.png)

**Additional context**

**Comment by denis-kasak** [comment]
> Hello there,
> 
> I am not the original issue poster but I believe to have found the solution (or the mistake). Also using searxng-docker, I also had that problem and the returned search url was also pointing to localhost.
> 
> My mistake was to run `docker compose up` inside the `searxng` directory (which contains the `settings.yml` file) thinking that it would read the parent directory of `docker-compose.yml` to read the `.env` file.
> 
> However, according to the docker documentation on [environment variables](https://docs.docker.com/compose/environment-variables/), in order for the `.env` to be read, the `docker compose up` command must be run in the same directory as the `.env` file.
> 
> The solution is either to run the command in the right directory (where the `.env` is), or to pass the file path to the `--env-file` option in the command, or to manually modify the `docker-compose.yml`.

This. 100x times this. This also helped me with the same issue although instead of using docker compose, i use just the docker container from the main repository. i was also wrongly executing `docker run ...` in the directory with the settings.yml instead of the main directory.

Thx
