### ISSUE TITLE
Can't find settings.yml in usual directory

### ISSUE THREAD

**Issue by pyvon** [searxng/searxng-docker#6]
Title is pretty self-explanatory, I did a fresh reinstall of searxng-docker today, and I can't find the **settings.yml** file that used to be in the /usr/local/searxng-docker/searx directory, which means I can't easily edit instance settings like before.

Was this intended? If so, where can I find the **settings.yml** file?

**Modifications in the .env file:**
* Set hostname to domain name
* Set letsencrypt email
* Comment SEARXNG_COMMAND=-f
* Morty key using readme instructions

**System configuration:**
* Ubuntu 20.04 on VPS

**Comment by dalf** [comment]
The PR #7 should fix your issue: the volume is now `/etc/searxng` not `/etc/searx`.
If it doesn't work, please report the issue.
