### ISSUE TITLE
hello i changed icons in searxng source and build docker image from this `$ git clone https://github.com/searxng/searxng.git

### ISSUE THREAD

**Issue by Krzysiekyt00** [searxng/searxng-docker#62]
hello i changed icons in searxng source and build docker image from this `$ git clone https://github.com/searxng/searxng.git
$ cd searxng
$ make docker.build
...
Successfully built 49586c016434
Successfully tagged searxng/searxng:latest
Successfully tagged searxng/searxng:1.0.0-209-9c823800-dirty

$ docker images`

i see that i have that image when i run '$docker images' but how do i start them?

_Originally posted by @Krzysiekyt00 in https://github.com/searxng/searxng-docker/discussions/61_

**Comment by return42** [comment]
> _Originally posted by @Krzysiekyt00 in https://github.com/searxng/searxng-docker/discussions/61_

Please do not open a (duplicate) issue when there is already a discussion .. I'm going to close this issue .. stay in https://github.com/searxng/searxng-docker/discussions/
