### ISSUE TITLE
Unable to use SSL cert 

### ISSUE THREAD

**Issue by Soulsender** [searxng/searxng-docker#65]
When I input my email in the `.env` file, I get an error when loading the page:
```
Error code: SSL_ERROR_INTERNAL_ERROR_ALERT
```
but when I leave the line commented out, I can load the page but I able not able to encrypt the traffic.

- The `docker-compose.yaml` file is left default, as is everything else except for the .env. 
- I have turned off the firewall so it's not that either.

I have this error when I run docker: (where SERVERIP is my ip address)
```
{"level":"error","ts":1660718437.6288152,"logger":"tls.obtain","msg":"will retry","error":"[SERVERIP] Obtain: subject does not qualify for a public certificate: SERVERIP","attempt":4,"retrying_in":300,"elapsed":300.052070216,"max_duration":2592000}

```

**Comment by dalf** [comment]
see https://github.com/searxng/searxng-docker/issues/66

**Comment by return42** [comment]
closed due to lack of feedback
