### ISSUE TITLE
Hello How to remove the about page in Searxng??

### ISSUE THREAD

**Issue by Mostafaibsharaf019** [searxng/searxng-docker#76]
### **_How to remove the about page in Searxng??_**

**Comment by dalf** [comment]
Duplicate of https://github.com/searx/searx/issues/3352

**Comment by Mostafaibsharaf019** [comment]
### _**Thank you**_

**Comment by Felmon** [comment]
> [searx/searx#3352](https://github.com/searx/searx/issues/3352) is in the wrong repository (SearXNG not searx) and there is no need to duplicate the issue at multiple locations.
> 
> You can't remove the about page by configuration, you have to hack the template.
> 
> You have to remove this line: https://github.com/searxng/searxng/blob/8a56e3d443d12c1b5f467bdffcb746747a7107ef/searx/templates/simple/base.html#L46
> 
> Since you use docker (?), what you can do is (⚠️ this was not tested) :
> 
> * you can copy / paste base.html
> * remove the line 46
> * mount your version of base.html in `/usr/local/searxng/searx/template/simple/base.html` in docker-compose.yml :
> 
> ```yaml
>   searxng:
>     container_name: searxng
>     image: searxng/searxng:latest   
>     volumes:
>        ./base.html: /usr/local/searxng/searx/template/simple/base.html
> ```

Hello, it don't work, please help to confirm this path is correct?
