### ISSUE TITLE
ERROR:searx

### ISSUE THREAD

**Issue by PlayTim** [searxng/searxng-docker#82]
hi when i start with docker-compose up this are in the console and the website doesnt work how kann i fix it i have do many times all that what in github are wirten. 
i think it is: cache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
but when i look in the uwsgi.ini configuration this is in it.

sorry for my bad english im german xD

console: 
searxng    | SearXNG version 2022.09.02-ea61d6ed
searxng    | Create /etc/searxng/uwsgi.ini
searxng    | Use existing /etc/searxng/settings.yml
searxng    | Listen on 0.0.0.0:8080
searxng    | [uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
searxng    | [uwsgi-static] added mapping for /static => /usr/local/searxng/sear                             x/static
searxng    | *** Starting uWSGI 2.0.20 (64bit) on [Fri Sep  2 08:55:10 2022] ***
searxng    | compiled with version: 11.2.1 20220219 on 21 December 2021 13:20:05
searxng    | os: Linux-5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC                              2022
searxng    | nodename: 3a62ad006116
searxng    | machine: x86_64
searxng    | clock source: unix
searxng    | pcre jit disabled
searxng    | detected number of CPU cores: 1
searxng    | current working directory: /usr/local/searxng
searxng    | detected binary path: /usr/sbin/uwsgi
searxng    | chdir() to /usr/local/searxng/searx/
searxng    | your memory page size is 4096 bytes
searxng    | detected max file descriptor number: 1048576
searxng    | building mime-types dictionary from file /etc/mime.types...1323 ent                             ry found
searxng    | lock engine: pthread robust mutexes
searxng    | thunder lock: disabled (you can enable it with --thunder-lock)
searxng    | *** Cache "searxngcache" initialized: 11MB (key: 2136 bytes, keys:                              4272000 bytes, data: 8192000 bytes, bitmap: 250 bytes) preallocated ***
searxng    | uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 4
searxng    | Python version: 3.10.5 (main, Jul 25 2022, 15:52:08) [GCC 11.2.1 20                             220219]
searxng    | Python main interpreter initialized at 0x7f3e5b428b50
searxng    | python threads support enabled
searxng    | your server socket listen backlog is limited to 100 connections
searxng    | your mercy for graceful operations on workers is 60 seconds
searxng    | mapped 241344 bytes (235 KB) for 4 cores
searxng    | *** Operational MODE: threaded ***
searxng    | added /usr/local/searxng/ to pythonpath.
searxng    | spawned uWSGI master process (pid: 6)
searxng    | spawned uWSGI worker 1 (pid: 10, cores: 4)
searxng    | cache sweeper thread enabled
searxng    | spawned 1 offload threads for uWSGI worker 1
**searxng    | 2022-09-02 08:55:11,410 ERROR:searx.shared: uwsgi.ini configuration                              error, add this line to your uwsgi.ini
searxng    | cache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bi                             tmap=1
searxng    | WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x7f3e                             5b428b50 pid: 10 (default app)**

**Comment by dalf** [comment]
> searxng | 2022-09-02 08:55:11,410 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
> searxng | cache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bi tmap=1

You can safely ignore this error.

https://github.com/searxng/searxng/pull/1513 is going to fix this message.

**Comment by PlayTim** [comment]
ok but when i open the websit this message ist shown : Die Verbindung mit dieser Website ist nicht sicher. what mean the website is not secure

**Comment by PlayTim** [comment]
on opera : ERR_SSL_PROTOCOL_ERROR

**Comment by PlayTim** [comment]
and this in the console:

caddy      | {"level":"error","ts":1662110120.0957708,"logger":"tls.obtain","msg":"will retry","error":"[172.          105.251.14] Obtain: subject does not qualify for a public certificate: 172.105.251.14","attempt":3,"retrying_          in":120,"elapsed":180.006549568,"max_duration":2592000}

**Comment by PlayTim** [comment]
now it works i dont know what i do but it works xD

**Comment by dalf** [comment]
https://github.com/searxng/searxng-docker/blob/d4f06df911e91803d6af48b8f0e060f08429b767/.env#L6

Just in case: SEARXNG_HOSTNAME has to be a hostname, not an IP address.
I close the issue since your instance is working.

**Comment by spectrapulse** [comment]
@dalf since https://github.com/searxng/searxng/pull/1513 has been closed. Can you please reopen the issue?
