### ISSUE TITLE
No longer shows results from google.

### ISSUE THREAD

**Issue by thealphabonanza** [searxng/searxng-docker#84]
I believe that this issue has been fixed by
https://github.com/searxng/searxng/pull/1643

**Comment by return42** [comment]
Please do not open an issue for a question which not belongs to this repository.  BTW you see that the linked PR is merged, that should answer your question.  For general questions please join the SearXNG community on Matrix  [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org)
