### ISSUE TITLE
errors with zero ssl

### ISSUE THREAD

**Issue by tibs01** [searxng/searxng-docker#89]
"HTTP 400 urn:ietf:params:acme:error:rejectedIdentifier - Invalid DNS identifier [searxng]"}
caddy      | {"level":"error","ts":1666348965.4351315,"logger":"tls.obtain","msg":"will retry","error":"[searxng] Obtain: [searxng] creating new order: attempt 1: https://acme.zerossl.com/v2/DV90/newOrder: HTTP 400 urn:ietf:params:acme:error:rejectedIdentifier - Invalid DNS identifier [searxng] (ca=https://acme.zerossl.com/v2/DV90)","attempt":5,"retrying_in":600,"elapsed":638.497552341,"max_duration":2592000}

it wont grab the ssl  its erroring 

caddy      | {"level":"info","ts":1666348326.947336,"logger":"http","msg":"waiting on internal rate limiter","identifiers":["searxng"],"ca":"https://acme-v02.api.letsencrypt.org/directory","account":"steve.gibbs@gmail.com"}
searxng    | detected max file descriptor number: 1048576
caddy      | {"level":"info","ts":1666348326.9474978,"logger":"http","msg":"done waiting on internal rate limiter","identifiers":["searxng"],"ca":"https://acme-v02.api.letsencrypt.org/directory","account":"steve.gibbs@gmail.com"}
searxng    | building mime-types dictionary from file /etc/mime.types...1323 entry found
caddy      | {"level":"error","ts":1666348327.8524797,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"searxng","issuer":"acme-v02.api.letsencrypt.org-directory","error":"HTTP 400 urn:ietf:params:acme:error:rejectedIdentifier - Error creating new order :: Cannot issue for \"searxng\": Domain name needs at least one dot"}
searxng    | lock engine: pthread robust mutexes
caddy      | {"level":"info","ts":1666348327.854164,"logger":"http","msg":"waiting on internal rate limiter","identifiers":["searxng"],"ca":"https://acme.zerossl.com/v2/DV90","account":"steve.gibbs@gmail.com"}

**Comment by dalf** [comment]
> Cannot issue for "searxng": Domain name needs at least one dot"

It seems the domain name is "searxng" (without dot or anything else).
What is your full domain name?
Update the .env file accordingly.

**Comment by return42** [comment]
closed due to lack of feedback
