### ISSUE TITLE
issues on the pi

### ISSUE THREAD

**Issue by tibs01** [searxng/searxng-docker#94]
im still getting errors on the raspberry pi 
as follows

":"will retry","error":"[192.168.1.50] Obtain: subject does not qualify for a pu                                                                                                             blic certificate: 192.168.1.50","attempt":5,"retrying_in":600,"elapsed":600.0228                                                                                                             01049,"max_duration":2592000}
caddy      | {"level":"info","ts":1667055380.699761,"logger":"tls.obtain","msg":                                                                                                             "obtaining certificate","identifier":"192.168.1.50"}
caddy      | {"level":"error","ts":1667055380.7028468,"logger":"tls.obtain","msg                                                                                                             ":"will retry","error":"[192.168.1.50] Obtain: subject does not qualify for a pu                                                                                                             blic certificate: 192.168.1.50","attempt":6,"retrying_in":1200,"elapsed":1200.02                                                                                                             7251616,"max_duration":2592000}
caddy      | {"level":"info","ts":1667055673.6432693,"logger":"http.log.access",                                                                                                             "msg":"handled request","request":{"remote_ip":"178.31.128.154","remote_port":"5                                                                                                             3461","proto":"HTTP/1.1","method":"GET","host":"82.26.160.198:81","uri":"/","hea                                                                                                             ders":{"User-Agent":["Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (K                                                                                                             HTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"],"Content-Length":["0"]}},                                                                                                             "user_id":"","duration":0.000168572,"size":0,"status":308,"resp_headers":{"Serve                                                                                                             r":["Caddy"],"Connection":["close"],"Location":["https://82.26.160.198/"],"Conte                                                                                                             nt-Type":[]}}

it wont work on the pi what so ever ive tried everything 

email  tibs01@steve-gibbs.co.uk if anyone can help me 

thanks steve

**Comment by return42** [comment]
duplicate https://github.com/searxng/searxng-docker/issues/90
