### ISSUE TITLE
Setting Up Cloudflare to work with Searxng

### ISSUE THREAD

**Issue by Catakang** [searxng/searxng-docker#95]
I am trying to setup a domain in Cloudflare that points to my instance of Searxng. But I get an error from cloudflare whenever I visit the site saying that Cloudflare is unable to establish an SSL connection to the origin server. How would I go fixing this?

**Comment by return42** [comment]
We do not support installations [where the owner doesn't control the final webserver that is serving the HTTPS requests to the users of the instance](https://github.com/searxng/searx-instances/pull/223).

Having a proxy (like cloudflare) which is not operated by the instance admin goes against the core principle of the privacy aspect of SearXNG.

**Comment by Catakang** [comment]
It would be pretty cool if you could delete this issue from existence.
