### ISSUE TITLE
Can't save settings - 502

### ISSUE THREAD

**Issue by Serpensin** [searxng/searxng-docker#99]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2022.11.19-b5371b7a

**How did you install SearXNG?**
Docker

**What happened?**
The search works just fine. But as soon as I click save in settings, I get an 502 error (even if I didn't change anything).
I only removed the 'Caddy' from the stack, because I'm using nginx.

**How To Reproduce**
Use the composer-file and remove the caddy part. Open portainer, stacks, web editor and post it there.

**Expected behavior**
I expect it to let me change settings.

**Screenshots & Logs**
[_redis_logs.txt](https://github.com/searxng/searxng/files/10079387/_redis_logs.txt)
[_searxng_logs.txt](https://github.com/searxng/searxng/files/10079388/_searxng_logs.txt)

**Comment by mrpaulblack** [comment]
Hi,
is there any response body in the HTTP 502 response that you can paste here? Can you try with a fresh browser profile in incognito mode for example if changing and saving the settings works there?

**Comment by Serpensin** [comment]
I found the issue. The composer-file set my SEARXNG_BASE_URL to localhost. (I didn't change it.)

**Comment by Serpensin** [comment]
Wrongfully closed. XD
I can save the settings in incognito. But in 'normal' browser, I get the 502 error.

**Comment by mrpaulblack** [comment]
ok I suspect that there is a setting in your local cookie that does not work with the searxng version. If you are ok with clearing your local settings by pressing the reset defaults button in the cookie tab of the preferences that should fix your issue.

**Comment by Serpensin** [comment]
I already tried that. I could reset it, but that didn't change anything.

**Comment by Serpensin** [comment]
Because of some other issues, I had to re-install my OS. Now it works.
I guess there was something messed-up with windows.

**Comment by p6002** [comment]
> ok I suspect that there is a setting in your local cookie that does not work with the searxng version. If you are ok with clearing your local settings by pressing the reset defaults button in the cookie tab of the preferences that should fix your issue.

Thanks! Works for me.
